# Numpy

## Cơ bản về numpy 

Numpy là viết tắt của `Numerical Python`, là một thư viện hỗ trợ tính toán trong Python  

In [1]:
L1 = list(range(0, 10))

In [2]:
L1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(L1)

list

In [4]:
type(L1[0])

int

Chuyển từ list của Python object thành array

In [5]:
import numpy as np
L2 = np.array(range(0, 10))
L2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(L2)

numpy.ndarray

**Lưu ý**: Khi làm việc với các dữ liệu dạng `vector` như R, ta cần chuyển định dạng `list` thành dạng `np.array`

## Tạo array cơ bản

In [7]:
# Tạo array zero
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# Tạo array 1
np.ones((2,3), dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.]])

**Lưu ý**: `dtype` là viết tắt của data type object - quy định kiểu cấu trúc dữ liệu trong array

In [9]:
# Tạo array 2x3 có giá trị 3.14

In [10]:
np.full((2,3), 3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [11]:
# Chuỗi từ 2:20
np.arange(2,20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# Array 3x3 giá trị random trong khoảng 0,1 (uniform distribution)

In [13]:
np.random.random((3,3))

array([[0.57631712, 0.41768034, 0.67665236],
       [0.05258287, 0.18273211, 0.43223421],
       [0.30320747, 0.28066927, 0.37133616]])

In [14]:
# Random theo phân phối chuẩn

In [15]:
np.random.normal(0,1, (3,3))

array([[-0.22007124,  0.90094741, -0.04069485],
       [ 1.22450006,  0.38860242, -0.46790895],
       [-1.16381358, -1.18725223, -0.60643464]])

In [16]:
# Random integer
np.random.randint(1, 10, (3,3))

array([[8, 4, 2],
       [5, 1, 5],
       [6, 7, 9]])

In [17]:
# Chia vector từ 0-5 thành 50 phần bằng nhau
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

## Các thuộc tính của array

Array có 3 thuộc tính sau:
- ndim: Số lượng chiều trong mảng
- shape: Chi tiết chiều trong mảng
- size: Số lượng phần tử trong mảng

In [18]:
import numpy as np
L1 = np.random.randint(10, size = (6))
L2 = np.random.normal(0, 1, size = (2,3))
L3 = np.random.normal(0, 1, size = (2,3,4))
L1
L2
L3

array([[[-0.12285773, -0.77931374,  0.17455533, -0.21175972],
        [ 0.42706988,  0.10828687,  0.72438997,  0.17277964],
        [ 0.29308257,  0.85646169, -0.08286228,  0.46052946]],

       [[-1.73434574,  0.43020879,  0.52509631, -0.75041061],
        [-1.1062507 ,  0.52989115,  0.21571298, -2.23330962],
        [ 0.42127505, -0.21586672,  1.4154433 ,  2.20955452]]])

In [19]:
L1

array([3, 5, 6, 4, 6, 7])

In [20]:
L1.ndim

1

In [21]:
L2.shape

(2, 3)

In [22]:
L3.size

24

**Lưu ý**: Trong Python, khi các thuộc tính của object, ta sử dụng không có dấu `()`, với hàm, ta sử dụng dấu `()`

## Trích xuất dữ liệu trong array

Trong array của numpy, ta chiết xuất dữ liệu tương tự như R. Tuy nhiên, do Python đánh số index từ 0 nên cần lưu ý.

In [23]:
my_array = np.random.randint(10, size = (3,3))

In [24]:
my_array

array([[1, 2, 9],
       [6, 4, 7],
       [2, 5, 1]])

In [25]:
my_array[0, 1]

2

In [26]:
my_array[1, 0]

6

In [27]:
my_array[2,1]

5

### Chiết xuất array theo chuỗi

In [28]:
x = np.arange(1, 10)

In [29]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Lưu ý**: Khi sử dụng `arange` trong numpy, chuỗi sẽ được thể hiện dạng `[a, b)`  

In [30]:
x[:5] #5 thành phần đầu tiên

array([1, 2, 3, 4, 5])

In [31]:
x[2:5] # Vị trí 3,4,5

array([3, 4, 5])

In [32]:
x[5:] # Tất cả các thành phần sau vị trí 5

array([6, 7, 8, 9])

In [33]:
x[::2] # Các thành phần ở vị trị lẻ

array([1, 3, 5, 7, 9])

In [34]:
x[::3] # Các thành phần cách nhau 3 chỉ số

array([1, 4, 7])

In [35]:
x[1::2] # Các thành phần ở vị trí lẻ, bắt đầu từ số 2

array([2, 4, 6, 8])

## Thay đổi chiều trong array

Sử dụng phương pháp `reshape()`

In [36]:
x = np.arange(1, 10)

In [37]:
type(np.array([1, 10]))

numpy.ndarray

In [38]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Fancy index

Ý tưởng của `fancy index` là sử dụng các vị trí trong array cũ để tạo array mới, trong khi đó, chiều của array mới được tạo thành từ `fancy index`

In [40]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
fancy_index = np.array([[0,2], [7,4]])
fancy_index

array([[0, 2],
       [7, 4]])

In [42]:
x[fancy_index]

array([[1, 3],
       [8, 5]])

## Các phép toán trong array

In [43]:
# Sort
x = np.array([1,3,2,9,6])

In [44]:
np.sort(x)

array([1, 2, 3, 6, 9])

In [45]:
# Sort với mảng hai chiều
y = np.random.randint(1,10, size = (3,3))

In [46]:
y

array([[7, 6, 7],
       [2, 8, 1],
       [6, 8, 4]])

In [47]:
np.sort(y, axis = 0) # Sort theo cột

array([[2, 6, 1],
       [6, 8, 4],
       [7, 8, 7]])

In [48]:
np.sort(y, axis = 1) # Sort theo dòng

array([[6, 7, 7],
       [1, 2, 8],
       [4, 6, 8]])

Các phép toán trong array của Python tương tự như R

## Biến đổi từ dataframe sang array

Các phép toán ứng dụng của machine learning chủ yếu làm việc với array. Trong khi đó, cấu trúc dữ liệu cơ bản khi làm việc về phân tích và khám phá dữ liệu lại là pd.DataFrame và pd.Series. Do đó, cần phải thành thạo việc biến đổi qua lại các kiểu dữ liệu trên

### List sang array

In [49]:
my_list = [1,2,3,4]

In [50]:
type(my_list)

list

In [51]:
# Biến đổi sang array
np.array(my_list)

array([1, 2, 3, 4])

### Series & DataFrame sang array

In [52]:
import pandas as pd
my_df = pd.DataFrame({
    'x' : [1,2,3],
    'y' : ['a', 'b', 'c']
})
my_df

x  y
0  1  a
1  2  b
2  3  c

In [53]:
# DF sang array
my_df.values

array([[1, 'a'],
       [2, 'b'],
       [3, 'c']], dtype=object)

In [54]:
type(my_df.values)

numpy.ndarray

In [55]:
new_array = my_df.values
new_array.shape

(3, 2)

In [56]:
# Series sang array
series_array =  my_df['x'].values

In [57]:
series_array.shape

(3,)

**Lưu ý**: Khi chuyển từ dạng Series sang array sẽ tạo thành 1 array 1 chiều. Do đó, khi làm việc với các thuật toán trong sklearn cần biến đổi shape để trở thành array dạng (n, 1) 

In [58]:
series_array.reshape(3, 1).shape

(3, 1)